baseURL: "https://jukri.github.io" 
title: Judith F. Kribelbauer
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Papers
          url: papers/
          weight: 1
        # - name: Courses
        #   url: courses/
        #   weight: 2
        # - name: Data
        #   url: data/
        #   weight: 3 
        # - name: Newsletter
        #   url: https://pmichaillat.substack.com
        #   weight: 4

params:
    description: "PostDoc at EPFL"
    author: Name
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Judith F. Kribelbauer
          subtitle: "Marie-Curie Postdoctoral Fellow at EPFL (École polytechnique fédérale de Lausanne) "
          imageUrl: "headshot.jpg"
          imageWidth: 280
          imageHeight: 280
          imageTitle: Judith F. Kribelbauer
          buttons:
            - name: Papers
              url: papers/
            # - name: Courses
            #   url: courses/
            # - name: Data
            #   url: data/
            # - name: Archive
            #   url: archive/
    socialIcons:
        # - name: CV
        #   url: cv.pdf
        - name: Email
          url: mailto:judith.kribelbauer@epfl.ch
        # - name: Location
        #   url: location/
        # - name: Office Hours
        #   url: officehours/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=E-3i3ikAAAAJ&hl=en
        # - name: YouTube
        #   url: https://www.youtube.com/@pmichaillat
        - name: GitHub
          url: https://github.com/jukri
        # - name: Substack
        #   url: https://pmichaillat.substack.com
        - name: Twitter
          url: https://twitter.com/jkribelbauer
        - name: LinkedIn
          url: https://www.linkedin.com/in/judithkribelbauer/?originalSubdomain=ch

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Judith F. Kribelbauer"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
